// src/views/about/Page.vue
<template>
  <main class="profile-page">
    <section class="relative block" style="height: 500px;">
      <div class="absolute top-0 w-full h-full bg-center bg-cover"
           :style="`background-image: url(${baseUrl}img/hero-bg.jpg);`"
      >
        <span id="blackOverlay" class="w-full h-full absolute opacity-50 bg-black"></span></div>
      <div class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden"
           style="height: 70px; transform: translateZ(0px);">
        <svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"
             version="1.1" viewBox="0 0 2560 100" x="0" y="0">
          <polygon class="text-gray-300 fill-current" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </section>
    <section class="relative py-16 bg-gray-300">
      <div class="container mx-auto px-4">
        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
          <div class="px-6">
            <div class="flex flex-wrap justify-center">
              <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
                <div class="relative"><img alt="..."
                                           :src="`${baseUrl}img/hero-bg.jpg`"
                                           class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16"
                                           style="max-width: 150px;">
                </div>
              </div>
              <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
                <div class="py-6 px-3 mt-32 sm:mt-0">
                  <button
                    class="bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1"
                    type="button" style="transition: all 0.15s ease 0s;">Connect
                  </button>
                </div>
              </div>
              <div class="w-full lg:w-4/12 px-4 lg:order-1">
                <div class="flex justify-center py-4 lg:pt-4 pt-8">
                  <div class="mr-4 p-3 text-center"><span
                    class="text-xl font-bold block uppercase tracking-wide text-gray-700">22</span><span
                    class="text-sm text-gray-500">Friends</span></div>
                  <div class="mr-4 p-3 text-center"><span
                    class="text-xl font-bold block uppercase tracking-wide text-gray-700">10</span><span
                    class="text-sm text-gray-500">Photos</span></div>
                  <div class="lg:mr-4 p-3 text-center"><span
                    class="text-xl font-bold block uppercase tracking-wide text-gray-700">89</span><span
                    class="text-sm text-gray-500">Comments</span></div>
                </div>
              </div>
            </div>
            <div class="text-center mt-12"><h3 class="text-4xl font-semibold leading-normal mb-2 text-gray-800 mb-2">
              About</h3>
              <div class="text-sm leading-normal mt-0 mb-2 text-gray-500 font-bold uppercase"><i
                class="fas fa-map-marker-alt mr-2 text-lg text-gray-500"></i> everywhere
              </div>
              <div class="mb-2 text-gray-700 mt-10"><i class="fas fa-briefcase mr-2 text-lg text-gray-500"></i>Solution
                Manager
              </div>
              <div class="mb-2 text-gray-700">
                <i class="fas fa-university mr-2 text-lg text-gray-500"></i>
                University of Computer Science
              </div>
            </div>
            <div class="mt-10 py-10 border-t border-gray-300 text-center">
              <div class="flex flex-wrap justify-center">
                <div class="w-full lg:w-9/12 px-4">

                  <p class="mb-4 text-lg leading-relaxed text-gray-800">
                    Protect.Earth came around after
                    <a href="https://philsturgeon.com/">Phil</a>
                    went riding
                    around Europe in the summer of 2019, the hottest year on record with the hottest three months on
                    record.
                  </p>
                  <p class="mb-4 text-lg leading-relaxed text-gray-800">
                    Phil was <a href="https://phil.bike/trees/">raising money for trees</a> with <a
                    href="https://offset.earth/">Offset Earth</a>, and after the tour lead to a lengthy injury he
                    wanted to find other ways to fight the climate crisis.
                  </p>
                  <p class="mb-4 text-lg leading-relaxed text-gray-800">Together with contributions from 50+ people, we
                    gather resources to help everyone find their next
                    piece of climate action. The climate crisis might be overwhelming when you start to understand the
                    severity of it all, but if we can get people on board with simplifying their lives, reducing their
                    footprint, offsetting the remaining footprint for barely any money, and reducing the insane
                    amounts of waste we all cause, our kids might have a chance.</p>

                  <a href="#pablo" class="font-normal text-pink-500">Show more</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script>
  export default {
    name: 'AboutPage',

    inject: ['baseUrl'],

  }
</script>

// src/pages/about.jsx
import React from 'react';
import { Layout, SuggestionForm } from '../components';
import Container from 'react-bootstrap/Container';
import Col from 'react-bootstrap/Col';
import Jumbotron from 'react-bootstrap/Jumbotron';
import Row from 'react-bootstrap/Row';

const AboutPage = () => (
  <Layout title="About">
    <Jumbotron
      style={{
        marginTop: '1rem',
        minHeight: '45vh',
        backgroundPosition: 'center center',
        backgroundSize: 'cover',
        backgroundImage:
          'url(https://source.unsplash.com/featured/1600x400?nature)',
      }}
    />
    <Container>
      <Row>
        <Col>
          <h1>About</h1>
          <p>
            Protect.Earth came around after{' '}
            <a href="https://philsturgeon.com/">Phil</a> went riding around
            Europe in the summer of 2019, the hottest year on record with the
            hottest three months on record.
          </p>
          <p>
            Phil was{' '}
            <a href="https://phil.bike/trees/">raising money for trees</a> with{' '}
            <a href="https://offset.earth/">Offset Earth</a>, and after the tour
            lead to a lengthy injury he wanted to find other ways to fight the
            climate crisis.
          </p>
          <p>
            Together with contributions from 50+ people, we gather resources to
            help everyone find their next piece of climate action. The climate
            crisis might be overwhelming when you start to understand the
            severity of it all, but if we can get people on board with
            simplifying their lives, reducing their footprint, offsetting the
            remaining footprint for barely any money, and reducing the insane
            amounts of waste we all cause, our kids might have a chance.
          </p>
        </Col>
      </Row>
    </Container>
    <Container>
      <SuggestionForm />
    </Container>
  </Layout>
);

export default AboutPage;
